### ISSUE TITLE
PHP Notice:  Constant DS already defined

### ISSUE THREAD

**Issue by elvetemedve** [ctasca/magefix#29]
Magefix depends on `phpmetrics/phpmetrics` which depends on `hoa/ruler` which requires `hoa/core`.

That package defines the `DS` constant here: https://github.com/hoaproject/Core/blob/master/Core.php#L134

When Magento is loaded, it [tries to define](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/Mage.php#L27) `DS` again, but can't because of the previous assignment.

I think `phpmetrics/phpmetrics` should be rather a dev dependency in composer.json.

**Comment by ctasca** [comment]
Hi ... Yes I noticed that while adding new feature Adapters for PHPspec. I'll fix this ASAP.
Temporary fix is to delete  hoa/ruler in vendor.

**Comment by elvetemedve** [comment]
Excellent, thank you.
