### ISSUE TITLE
Cannot install package due to version constraints

### ISSUE THREAD

**Issue by elvetemedve** [ctasca/magefix#35]
I cannot update this package to the latest _3.0.1_, because it requires a different _phpspec/phpspec_ version than I use on my project. 
Can you please move all development related packages to list of **dev dependencies** (like behat/behat, phpspec/phpspec)?
Thank you.

**Comment by ctasca** [comment]
Hi Gèza...

Sure I'll fix it asap. Thanks

**Comment by ctasca** [comment]
Hi Geza,

Should be fixed now in 3.0.2 release. Can you give it a try and let me know if you have more issues?

**Comment by elvetemedve** [comment]
Hi Carlo,

It's working perfectly now. Thank you for the fix. :+1:
